language: ruby
cache: bundler
rvm:
  - 2.7
  - jruby
os: ubuntu bionic 18.04
branches:
  only:
  - master
  - /^testing-.*$/
  - /^dev-.*$/
before_install:
  - gem install bundler
  - rvm list known
  - rvm install 2.7.1
install: bundle install
gemspec: ./notion_api.gemspec
script: rspec spec