language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
branches:
  only:
  - master
  - /^deploy-.*$/
before_install:
  - gem install bundler
  - rvm list known
install: bundle install
script: rspec spec
notifications:
  email:
    recipients:
      - danielmurph8@gmail.com
    on_success: never
    on_failure: always